pipeline {
   // agent { label 'any' }
agent any
// environment{
 //    DOCKER_HUB_CREDENTIALS = credentials('DOCKER_HUB_CRED')
  //   }
    stages {
        stage('checkout git branch') {
            steps {
git credentialsId: 'github', url: 'https://github.com/dharma0907/Edurakaproj2.git'
                     checkout scm
            }
        }
stage('docker build image') {
            // build docker image
            steps {
                sh "docker build --no-cache -t train-v${env.BUILD_NUMBER} -f trainapp/cicd/Dockerfile ."
            }
        }
        stage('docker tag the build') {
            steps {
               
                sh "docker tag train-v${env.BUILD_NUMBER} demo.goharbor.io/train/train:v${env.BUILD_NUMBER}"    
            }
        }
       stage('docker push image to nexus'){         
steps{

sh "echo haiiiiiiiiiiiiiiiiiiiiiiiiiiiiii"

sh "echo haiiiiiiiiiiiiiiiiiiiiiiiiiii++++++++"

withCredentials([usernameColonPassword(credentialsId: 'nexus', variable: 'docker_pass')]) {

    sh "echo nexus registry"    
               sh "docker push 172.31.29.22:8081/train/train:v${env.BUILD_NUMBER}"
           }
      }
}
      stage('upade helm and run '){
        steps{
            sh "pwd"
           sh "/usr/local/bin/helm --kubeconfig /home/edureka/.kube/admin.conf upgrade --install train harbor-test/train --set image.tag='v${env.BUILD_NUMBER}' --namespace trainschdule -f trainapp/cicd/values.yaml"
         } 
      } 

}
}

